### ISSUE TITLE
Invalid libraries being generated for Windows

### ISSUE THREAD

**Issue by hhslepicka** [conda-forge/epics-base-feedstock#3]
Issue:
The current build of epics-base with mingw32-make is producing an invalid library and creating issues for pyepics tests and clients using Windows.

Also, we need to make sure to add `%PREFIX%\epics\lib\windows-64;%PREFIX%\epics\bin\windows-64;` to the `%PATH%` using `%PREFIX%\etc\conda\activate.d\`.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by beenje** [comment]
@hhslepicka do you agree this can be closed after https://github.com/conda-forge/epics-base-feedstock/pull/6 ?

**Comment by hhslepicka** [comment]
@beenje I will give it a try and report back.

**Comment by hhslepicka** [comment]
@beenje I just tried it at my Windows VM and it is working great! Thank you.
